---@meta

--- NOTE: In this file, underscores (_) in names represent spaces from Blueprint.
--- For example: 'Apply_Damage' in Lua corresponds to 'Apply Damage' in Blueprint.
--- Access these using bracket notation: object["Apply Damage"]

---@diagnostic disable: undefined-doc-name
---@class BlueprintCore
---Blueprint Core
---
--- Properties
---Pointer to the skeleton class; this is regenerated any time a member variable or function is added but
---      is usually incomplete (no code or hidden autogenerated variables are added to it)
---@field SkeletonGeneratedClass Class
---Pointer to the 'most recent' fully generated class
---@field GeneratedClass Class
---BackCompat:  Whether or not we need to purge references in this blueprint to the skeleton generated during compile-on-load
---@field bLegacyNeedToPurgeSkelRefs boolean
local BlueprintCore = {}

--- Methods
return BlueprintCore
