---@meta

--- NOTE: In this file, underscores (_) in names represent spaces from Blueprint.
--- For example: 'Apply_Damage' in Lua corresponds to 'Apply Damage' in Blueprint.
--- Access these using bracket notation: object["Apply Damage"]

---@diagnostic disable: undefined-doc-name
---@class Font
---A font object, for use by Slate, UMG, and Canvas.
---A font can either be:
---  * Runtime cached - The font contains a series of TTF files that combine to form a composite font. The glyphs are cached on demand when required at runtime.
---  * Offline cached - The font contains a series of textures containing pre-baked cached glyphs and their associated texture coordinates.
---
--- Properties
---What kind of font caching should we use? This controls which options we see
---@field FontCacheType EFontCacheType
---List of characters in the font.  For a MultiFont, this will include all characters in all sub-fonts!  Thus,
---              the number of characters in this array isn't necessary the number of characters available in the font
---@field Characters FontCharacter[]
---Textures that store this font's glyph image data //NOTE: Do not expose this to the editor as it has nasty crash potential
---@field Textures Texture2D[]
---True if font is 'remapped'.  That is, the character array is not a direct mapping to unicode values.  Instead,
---              all characters are indexed indirectly through the CharRemap array
---@field IsRemapped integer
---Font metrics.
---@field EmScale number
---@todo document
---@field Ascent number
---@todo document
---@field Descent number
---@todo document
---@field Leading number
---Default horizontal spacing between characters when rendering text with this font
---@field Kerning integer
---Options used when importing this font
---@field ImportOptions FontImportOptionsData
---Number of characters in the font, not including multiple instances of the same character (for multi-fonts).
---              This is cached at load-time or creation time, and is never serialized.
---@field NumCharacters integer
---The maximum height of a character in this font.  For multi-fonts, this array will contain a maximum
---              character height for each multi-font, otherwise the array will contain only a single element.  This is
---              cached at load-time or creation time, and is never serialized.
---@field MaxCharHeight integer[]
---Scale to apply to the font.
---@field ScalingFactor number
---The default size of the font used for legacy Canvas APIs that don't specify a font size
---@field LegacyFontSize integer
---The default font name to use for legacy Canvas APIs that don't specify a font name
---@field LegacyFontName string
---Embedded composite font data
---@field CompositeFont CompositeFont
local Font = {}

--- Methods
return Font
