---@meta

--- NOTE: In this file, underscores (_) in names represent spaces from Blueprint.
--- For example: 'Apply_Damage' in Lua corresponds to 'Apply Damage' in Blueprint.
--- Access these using bracket notation: object["Apply Damage"]

---@diagnostic disable: undefined-doc-name
---@class HitResult
---Structure containing information about one hit of a trace, such as point of impact and surface normal at that point.
---
--- Properties
---Face index we hit (for complex hits with triangle meshes).
---@field FaceIndex integer
---'Time' of impact along trace direction (ranging from 0.0 to 1.0) if there is a hit, indicating time between TraceStart and TraceEnd.
---For swept movement (but not queries) this may be pulled back slightly from the actual time of impact, to prevent precision problems with adjacent geometry.
---@field Time number
---The distance from the TraceStart to the Location in world space. This value is 0 if there was an initial overlap (trace started inside another colliding object).
---@field Distance number
---The location in world space where the moving shape would end up against the impacted object, if there is a hit. Equal to the point of impact for line tests.
---Example: for a sphere trace test, this is the point where the center of the sphere would be located when it touched the other object.
---For swept movement (but not queries) this may not equal the final location of the shape since hits are pulled back slightly to prevent precision issues from overlapping another surface.
---@field Location Vector_NetQuantize
---Location in world space of the actual contact of the trace shape (box, sphere, ray, etc) with the impacted object.
---Example: for a sphere trace test, this is the point where the surface of the sphere touches the other object.
---@note: In the case of initial overlap (bStartPenetrating=true), ImpactPoint will be the same as Location because there is no meaningful single impact point to report.
---@field ImpactPoint Vector_NetQuantize
---Normal of the hit in world space, for the object that was swept. Equal to ImpactNormal for line tests.
---This is computed for capsules and spheres, otherwise it will be the same as ImpactNormal.
---Example: for a sphere trace test, this is a normalized vector pointing in towards the center of the sphere at the point of impact.
---@field Normal Vector_NetQuantizeNormal
---Normal of the hit in world space, for the object that was hit by the sweep, if any.
---For example if a sphere hits a flat plane, this is a normalized vector pointing out from the plane.
---In the case of impact with a corner or edge of a surface, usually the "most opposing" normal (opposed to the query direction) is chosen.
---@field ImpactNormal Vector_NetQuantizeNormal
---Start location of the trace.
---For example if a sphere is swept against the world, this is the starting location of the center of the sphere.
---@field TraceStart Vector_NetQuantize
---End location of the trace; this is NOT where the impact occurred (if any), but the furthest point in the attempted sweep.
---For example if a sphere is swept against the world, this would be the center of the sphere if there was no blocking hit.
---@field TraceEnd Vector_NetQuantize
---If this test started in penetration (bStartPenetrating is true) and a depenetration vector can be computed,
---this value is the distance along Normal that will result in moving out of penetration.
---If the distance cannot be computed, this distance will be zero.
---@field PenetrationDepth number
---If the hit result is from a collision this will have extra info about the item that hit the second item.
---@field MyItem integer
---Extra data about item that was hit (hit primitive specific).
---@field Item integer
---Index to item that was hit, also hit primitive specific.
---@field ElementIndex integer
---Indicates if this hit was a result of blocking collision. If false, there was no hit or it was an overlap/touch instead.
---@field bBlockingHit boolean
---Whether the trace started in penetration, i.e. with an initial blocking overlap.
---In the case of penetration, if PenetrationDepth > 0.f, then it will represent the distance along the Normal vector that will result in
---minimal contact between the swept shape and the object that was hit. In this case, ImpactNormal will be the normal opposed to movement at that location
---(ie, Normal may not equal ImpactNormal). ImpactPoint will be the same as Location, since there is no single impact point to report.
---@field bStartPenetrating boolean
---Physical material that was hit.
---@note Must set bReturnPhysicalMaterial on the swept PrimitiveComponent or in the query params for this to be returned.
---@field PhysMaterial any
---Handle to the object hit by the trace.
---@field HitObjectHandle ActorInstanceHandle
---PrimitiveComponent hit by the trace.
---@field Component any
---Name of bone we hit (for skeletal meshes).
---@field BoneName string
---Name of the _my_ bone which took part in hit event (in case of two skeletal meshes colliding).
---@field MyBoneName string
local HitResult = {}
return HitResult
