---@meta

--- NOTE: In this file, underscores (_) in names represent spaces from Blueprint.
--- For example: 'Apply_Damage' in Lua corresponds to 'Apply Damage' in Blueprint.
--- Access these using bracket notation: object["Apply Damage"]

---@diagnostic disable: undefined-doc-name
---@class MaterialExpression
---Material Expression
---
--- Properties
---@field MaterialExpressionEditorX integer
---@field MaterialExpressionEditorY integer
---Expression's Graph representation
---@field GraphNode EdGraphNode
---If exists, expresssion containing this expression within its subgraph.
---@field SubgraphExpression MaterialExpression
---GUID to uniquely identify this node, to help the tutorials out
---@field MaterialExpressionGuid Guid
---The material that this expression is currently being compiled in.
---This is not necessarily the object which owns this expression, for example a preview material compiling a material function's expressions.
---@field Material Material
---The material function that this expression is being used with, if any.
---This will be NULL if the expression belongs to a function that is currently being edited,
---@field Function MaterialFunction
---A description that level designers can add (shows in the material editor UI).
---@field Desc string
---Set to true by RecursiveUpdateRealtimePreview() if the expression's preview needs to be updated in realtime in the material editor.
---@field bRealtimePreview boolean
---If true, we should update the preview next render. This is set when changing bRealtimePreview.
---@field bNeedToUpdatePreview boolean
---Indicates that this is a 'parameter' type of expression and should always be loaded (ie not cooked away) because we might want the default parameter.
---@field bIsParameterExpression boolean
---If true, the comment bubble will be visible in the graph editor
---@field bCommentBubbleVisible boolean
---If true, use the output name as the label for the pin
---@field bShowOutputNameOnPin boolean
---If true, changes the pin color to match the output mask
---@field bShowMaskColorsOnPin boolean
---If true, do not render the preview window for the expression
---@field bHidePreviewWindow boolean
---If true, show a collapsed version of the node
---@field bCollapsed boolean
---Whether the node represents an input to the shader or not.  Used to color the node's background.
---@field bShaderInputData boolean
---Whether to draw the expression's inputs.
---@field bShowInputs boolean
---Whether to draw the expression's outputs.
---@field bShowOutputs boolean
---Localized categories to sort this expression into...
---@field MenuCategories string[]
---The expression's outputs, which are set in default properties by derived classes.
---@field Outputs ExpressionOutput[]
local MaterialExpression = {}

--- Methods
return MaterialExpression
