---@meta

--- NOTE: In this file, underscores (_) in names represent spaces from Blueprint.
--- For example: 'Apply_Damage' in Lua corresponds to 'Apply Damage' in Blueprint.
--- Access these using bracket notation: object["Apply Damage"]

---@diagnostic disable: undefined-doc-name
---@class MinimalViewInfo
---Minimal View Info
---
--- Properties
---Location
---@field Location Vector
---Rotation
---@field Rotation Rotator
---The horizontal field of view (in degrees) in perspective mode (ignored in orthographic mode).
---@field FOV number
---The originally desired horizontal field of view before any adjustments to account for different aspect ratios
---@field DesiredFOV number
---The horizontal field of view (in degrees) used for primitives tagged as "IsFirstPerson".
---@field FirstPersonFOV number
---The scale to apply to primitives tagged as "IsFirstPerson". This is used to scale down primitives towards the camera such that they are small enough not to intersect with the scene.
---@field FirstPersonScale number
---The desired width (in world units) of the orthographic view (ignored in Perspective mode)
---@field OrthoWidth number
---Option for the Ortho camera to automatically calculated the near/far plane
---@field bAutoCalculateOrthoPlanes boolean
---Manually adjusts the planes of this camera, maintaining the distance between them. Positive moves out to the farplane, negative towards the near plane
---@field AutoPlaneShift number
---Adjusts the near/far planes and the view origin of the current camera automatically to avoid clipping and light artefacting
---@field bUpdateOrthoPlanes boolean
---If UpdateOrthoPlanes is enabled, this setting will use the cameras current height to compensate the distance to the general view (as a pseudo distance to view target when one isn't present)
---@field bUseCameraHeightAsViewTarget boolean
---The near plane distance of the orthographic view (in world units)
---@field OrthoNearClipPlane number
---The far plane distance of the orthographic view (in world units)
---@field OrthoFarClipPlane number
---The near plane distance of the perspective view (in world units). Set to a negative value to use the default global value of GNearClippingPlane
---@field PerspectiveNearClipPlane number
---Aspect Ratio (Width/Height)
---@field AspectRatio number
---If bConstrainAspectRatio is true, black bars will be added if the destination view has a different aspect ratio than this camera requested.
---@field bConstrainAspectRatio boolean
---If bUseFirstPersonParameters is true, FirstPersonFOV and FirstPersonScale should be applied to primitives tagged as "IsFirstPerson".
---@field bUseFirstPersonParameters boolean
---If true, account for the field of view angle when computing which level of detail to use for meshes.
---@field bUseFieldOfViewForLOD boolean
---The type of camera
---@field ProjectionMode integer
---Indicates if PostProcessSettings should be applied.
---@field PostProcessBlendWeight number
---Post-process settings to use if PostProcessBlendWeight is non-zero.
---@field PostProcessSettings PostProcessSettings
---Off-axis / off-center projection offset as proportion of screen dimensions
---@field OffCenterProjectionOffset Vector2D
---Resolution fraction that scales with the amount of overscan added to the view
---@field OverscanResolutionFraction number
---The fraction between 0.0 and 1.0 of the view to crop to during the final post process upscale, with 1.0 meaning no crop
---@field CropFraction number
---Experimental: The fraction for each edge between 0.0 and 1.0 of the view to crop to during the final post process upscale, with 1.0 meaning no crop.
---By convention, X is the left edge, Y is the right edge, Z is the top edge, and W is the bottom edge. Stacks with uniform CropFraction.
---@field AsymmetricCropFraction Vector4f
local MinimalViewInfo = {}
return MinimalViewInfo
