---@meta

--- NOTE: In this file, underscores (_) in names represent spaces from Blueprint.
--- For example: 'Apply_Damage' in Lua corresponds to 'Apply Damage' in Blueprint.
--- Access these using bracket notation: object["Apply Damage"]

---@diagnostic disable: undefined-doc-name

---@class PhysicalMaterial
---Physical materials are used to define the response of a physical object when interacting dynamically with the world.
---
--- Properties
---
---Friction value of surface, controls how easily things can slide on this surface (0 is frictionless, higher values increase the amount of friction)
---@field Friction number
---Static Friction value of surface, controls how easily things can slide on this surface (0 is frictionless, higher values increase the amount of friction)
---@field StaticFriction number
---Friction combine mode, controls how friction is computed for multiple materials.
---@field FrictionCombineMode integer
---If set we will use the FrictionCombineMode of this material, instead of the FrictionCombineMode found in the project settings.
---@field bOverrideFrictionCombineMode boolean
---Restitution or 'bounciness' of this surface, between 0 (no bounce) and 1 (outgoing velocity is same as incoming).
---@field Restitution number
---Restitution combine mode, controls how restitution is computed for multiple materials.
---@field RestitutionCombineMode integer
---If set we will use the RestitutionCombineMode of this material, instead of the RestitutionCombineMode found in the project settings.
---@field bOverrideRestitutionCombineMode boolean
---Used with the shape of the object to calculate its mass properties. The higher the number, the heavier the object. g per cubic cm.
---@field Density number
---How low the linear velocity can be before solver puts body to sleep.
---@field SleepLinearVelocityThreshold number
---How low the angular velocity can be before solver puts body to sleep.
---@field SleepAngularVelocityThreshold number
---How many ticks we can be under thresholds for before solver puts body to sleep.
---@field SleepCounterThreshold integer
---Used to adjust the way that mass increases as objects get larger. This is applied to the mass as calculated based on a 'solid' object.
---In actuality, larger objects do not tend to be solid, and become more like 'shells' (e.g. a car is not a solid piece of metal).
---Values are clamped to 1 or less.
---@field RaiseMassToPower number
---@field DestructibleDamageThresholdScale number
---@field PhysicalMaterialProperty PhysicalMaterialPropertyBase
---To edit surface type for your project, use ProjectSettings/Physics/PhysicalSurface section
---@field SurfaceType integer
---@field Strength PhysicalMaterialStrength
---@field DamageModifier PhysicalMaterialDamageModifier
---Color used to represent this material in certain debug views (e.g. landscape collision)
---@field DebugColor LinearColor
---Experimental material properties are enabled via the p.PhysicalMaterial.ShowExperimentalProperties console variable.
---              NOTE: These are _experimental_ properties which may change. Use at your own risk!
---@field bShowExperimentalProperties boolean
---For enable soft collision shell thickness mode
---@field SoftCollisionMode EPhysicalMaterialSoftCollisionMode
---Thickness of the layer just inside the collision shape in which contact is considered "soft".
---              The units depend on SoftCollisionMode
---@field SoftCollisionThickness number
---A friction (positional) impulse of at least this magnitude may be applied,
---              regardless the normal force. This is analogous to adding only the lateral part of a
---              "stickiness" to a material
---@field BaseFrictionImpulse number
local PhysicalMaterial = {}

--- Methods
return PhysicalMaterial
