---@meta

--- NOTE: In this file, underscores (_) in names represent spaces from Blueprint.
--- For example: 'Apply_Damage' in Lua corresponds to 'Apply Damage' in Blueprint.
--- Access these using bracket notation: object["Apply Damage"]

---@diagnostic disable: undefined-doc-name
---@class RepMovement
---Replicated movement data of our RootComponent.
---Struct used for efficient replication as velocity and location are generally replicated together (this saves a repindex)
---and velocity.Z is commonly zero (most position replications are for walking pawns).
---
--- Properties
---Velocity of component in world space
---@field LinearVelocity Vector
---Velocity of rotation for component (only valid if bRepPhysics is set)
---@field AngularVelocity Vector
---Location in world space
---@field Location Vector
---Current rotation
---@field Rotation Rotator
---Acceleration of component in world space. Only valid if bRepAcceleration is set.
---@field Acceleration Vector
---If set, RootComponent should be sleeping.
---@field bSimulatedPhysicSleep boolean
---If set, additional physic data (angular velocity) will be replicated.
---@field bRepPhysics boolean
---If set, additional acceleration data will be replicated.
---@field bRepAcceleration boolean
---Server physics step
---@field ServerFrame integer
---ID assigned by server used to ensure determinism by physics.
---@field ServerPhysicsHandle integer
---Allows tuning the compression level for the replicated location vector. You should only need to change this from the default if you see visual artifacts.
---@field LocationQuantizationLevel EVectorQuantization
---Allows tuning the compression level for the replicated velocity vectors. You should only need to change this from the default if you see visual artifacts.
---@field VelocityQuantizationLevel EVectorQuantization
---Allows tuning the compression level for replicated rotation. You should only need to change this from the default if you see visual artifacts.
---@field RotationQuantizationLevel ERotatorQuantization
local RepMovement = {}
return RepMovement
