---@meta

--- NOTE: In this file, underscores (_) in names represent spaces from Blueprint.
--- For example: 'Apply_Damage' in Lua corresponds to 'Apply Damage' in Blueprint.
--- Access these using bracket notation: object["Apply Damage"]

---@diagnostic disable: undefined-doc-name

---@class SkeletalMeshSourceModel
---Skeletal Mesh Source Model
---
--- Properties
---
---@field TriangleCount integer
---@field VertexCount integer
---@field Bounds BoxSphereBounds
---List of all alternate skin weight profiles stored on the mesh,
---NOTE: The default value is single-entry array with NAME_None to mark
---that this value has not been initialized yet / TOptional does not work
---with containers.
---@field CachedSkinWeightProfileNames string[]
---List of all morph targets stored on the mesh.
---@field CachedMorphTargetNames string[]
---@field CachedHasVertexColors any
---@field CachedVertexColorGuid Guid
---Bulk data containing mesh description from imported or modeled geometry.
---If the bulk data within is empty, the LOD is autogenerated (for LOD1+).
---@field MeshDescriptionBulkData SkeletalMeshDescriptionBulkData
local SkeletalMeshSourceModel = {}

--- Constructor
---@return SkeletalMeshSourceModel
---@param TriangleCount integer
---@param VertexCount integer
---@param Bounds BoxSphereBounds
---@param CachedSkinWeightProfileNames string[]
---@param CachedMorphTargetNames string[]
---@param CachedHasVertexColors any
---@param CachedVertexColorGuid Guid
---@param MeshDescriptionBulkData SkeletalMeshDescriptionBulkData
function SkeletalMeshSourceModel.new(TriangleCount, VertexCount, Bounds, CachedSkinWeightProfileNames, CachedMorphTargetNames, CachedHasVertexColors, CachedVertexColorGuid, MeshDescriptionBulkData)
    local self = {}
    self.TriangleCount = TriangleCount
    self.VertexCount = VertexCount
    self.Bounds = Bounds
    self.CachedSkinWeightProfileNames = CachedSkinWeightProfileNames
    self.CachedMorphTargetNames = CachedMorphTargetNames
    self.CachedHasVertexColors = CachedHasVertexColors
    self.CachedVertexColorGuid = CachedVertexColorGuid
    self.MeshDescriptionBulkData = MeshDescriptionBulkData
    return self
end

return SkeletalMeshSourceModel
