---@meta

--- NOTE: In this file, underscores (_) in names represent spaces from Blueprint.
--- For example: 'Apply_Damage' in Lua corresponds to 'Apply Damage' in Blueprint.
--- Access these using bracket notation: object["Apply Damage"]

---@diagnostic disable: undefined-doc-name
---@class StaticMeshSourceModel
---Source model from which a renderable static mesh is built.
---
--- Properties
---Bulk data containing mesh description.
---New assets store their source data here instead of in the RawMeshBulkData.
---If the bulk data within is empty, the LOD is autogenerated (for LOD1+).
---@field StaticMeshDescriptionBulkData StaticMeshDescriptionBulkData
---Settings applied when building the mesh.
---@field BuildSettings MeshBuildSettings
---Reduction settings to apply when building render data.
---@field ReductionSettings MeshReductionSettings
---@field CacheMeshDescriptionTrianglesCount integer
---@field CacheMeshDescriptionVerticesCount integer
---@field LODDistance number
---ScreenSize to display this LOD.
---The screen size is based around the projected diameter of the bounding
---sphere of the model. i.e. 0.5 means half the screen's maximum dimension.
---@field ScreenSize PerPlatformFloat
---The file path that was used to import this LOD.
---@field SourceImportFilename string
---Whether this LOD was imported in the same file as the base mesh.
---@field bImportWithBaseMesh boolean
local StaticMeshSourceModel = {}
return StaticMeshSourceModel
